### ISSUE TITLE
ImportError on first use

### ISSUE THREAD

**Issue by bashinho** [soxoj/marple#20]
git clone https://github.com/soxoj/marple.git
cd marple
pip3 install -r requirements.txt 

$ ./marple.py soxoj
Traceback (most recent call last):
  File "./marple.py", line 15, in <module>
    from aiohttp_socks import ProxyConnector
  File "/home/[*******]/.local/lib/python3.8/site-packages/aiohttp_socks/__init__.py", line 5, in <module>
    from .connector import (
  File "/home/[*******]/.local/lib/python3.8/site-packages/aiohttp_socks/connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/home/[*******]/.local/lib/python3.8/site-packages/aiohttp/helpers.py)

System: Linux Mint Xfce on Proxmox

**Comment by soxoj** [comment]
Can you please check you aiohttp version?
```pip freeze | grep aiohttp```

**Comment by bashinho** [comment]
$ pip freeze | grep aiohttp
aiohttp==3.8.1
aiohttp-socks==0.7.1

**Comment by soxoj** [comment]
Please, try to run `pip install --upgrade aiohttp && pip install --force-reinstall aiohttp-socks`
Thread: https://github.com/twintproject/twint/issues/1297

**Comment by bashinho** [comment]
that worked. thank you

Links: total collected 998 / unique with username in URL 617 / reliable 60 / documents 14
