### ISSUE TITLE
ImportError: cannot import name 'Aol' from 'search_engines' 

### ISSUE THREAD

**Issue by andre-santos1** [soxoj/marple#22]
When running:

./marple.py [my_target_username]

I get:

Traceback (most recent call last):

  File "/home/osint/Programas/marple/./marple.py", line 21, in <module>

    from search_engines import Aol, Ask, Qwant, Bing, Yahoo, Startpage, Dogpile, Mojeek, Torch, Duckduckgo

ImportError: cannot import name 'Aol' from 'search_engines' (/usr/local/lib/python3.10/dist-packages/search_engines/__init__.py)

**Comment by soxoj** [comment]
Please, do requirements install, you are using old version of search_engines package.
