### ISSUE TITLE
Ошибка No module named 'yandex_search'

### ISSUE THREAD

**Issue by sai84** [soxoj/marple#4]
Вот такую ошибку выдает:

Traceback (most recent call last):
  File "/home/panther/marple/marple.py", line 13, in <module>
    import yandex_search
ModuleNotFoundError: No module named 'yandex_search'

**Comment by soxoj** [comment]
Я обновил `requirements.txt`, теперь достаточно заново установить зависимости.
Спасибо за фидбек!
